typescript: true

commandDir: lib/commands
commandMakeDir: src/commands
extendDir: lib/extends
extendMakeDir: src/extends
hookDir: lib/hooks
hookMakeDir: src/hooks

$plugin:
  redis:
    defaultConnection: redis
    connection:
      redis:
        host: 127.0.0.1
        port: 6379
  semo:
    repl:
      hook: true
      extract: Semo.hooks.redis.redis
